### ISSUE TITLE
Rename feature does not work as expected

### ISSUE THREAD

**Issue by Kv4sir** [DarwinSPL/DarwinSPL#16]
- After renaming a feature, the diagram editor is not updated
- After assigning a date, it can't be removed anymore
- Deleting a name doesn't work (dirty flag is also not set)

**Comment by mnieke** [comment]
Seems to happen if right-click -> rename is uesd.

Workaround for the time being:
double-click on feature to rename it should work properly.

**Comment by mnieke** [comment]
Can you please have a look whether this issue is still a problem?
