### ISSUE TITLE
Rearranging children leads to a wrong visual representation

### ISSUE THREAD

**Issue by Kv4sir** [DarwinSPL/DarwinSPL#17]
Changed the parent feature for two features under the root to another feature (done internally correctly, but drawn wrong):
![screenshot from 2017-09-11 13-47-23](https://user-images.githubusercontent.com/9748680/30273142-ff0dcfd8-96f7-11e7-9215-c1cf7a83cff6.png)
Proof for internal correctness:
![screenshot from 2017-09-11 13-47-47](https://user-images.githubusercontent.com/9748680/30273152-06c233f4-96f8-11e7-97fa-bde8bcfbce0a.png)

**Comment by mnieke** [comment]
Could you please attach the .hyfeature and .hylayout file.
For me it seems to work

**Comment by Kv4sir** [comment]
[de.tu_bs.cs.isf.jxmapviewer.spl.zip](https://github.com/DarwinSPL/DarwinSPL/files/1292523/de.tu_bs.cs.isf.jxmapviewer.spl.zip)

**Comment by mnieke** [comment]
I am now able to reproduce it:
Create F1 under root.
Go to date t1 and create F2 under root. Move F1 under F2.
I'm trying to fix the attached model in the mean time.

**Comment by mnieke** [comment]
Fixed model. Please delete .hylayout file before using it

[NavigationSystem.zip](https://github.com/DarwinSPL/DarwinSPL/files/1292624/NavigationSystem.zip)
