### ISSUE TITLE
Wrong calculation of collapsed root childs

### ISSUE THREAD

**Issue by Kv4sir** [DarwinSPL/DarwinSPL#18]
Following feature project:
![screenshot from 2017-09-11 14-05-04](https://user-images.githubusercontent.com/9748680/30273666-497c27d4-96fa-11e7-85d6-02cd0c3d9686.png)
leads to a wrong counter of children for the **root** feature:
![screenshot from 2017-09-11 14-05-14](https://user-images.githubusercontent.com/9748680/30273681-57dcacb8-96fa-11e7-8f80-1990aa6b8404.png)

**Comment by mnieke** [comment]
Can you please attach the .hyfeature model?

**Comment by Kv4sir** [comment]
[NavigationSystem.hyfeature.zip](https://github.com/DarwinSPL/DarwinSPL/files/1292521/NavigationSystem.hyfeature.zip)

**Comment by mnieke** [comment]
Related to #17
