### ISSUE TITLE
Collapsed children are not expanded when changing date

### ISSUE THREAD

**Issue by Kv4sir** [DarwinSPL/DarwinSPL#19]
Before changing date:
![screenshot from 2017-09-11 14-07-28](https://user-images.githubusercontent.com/9748680/30273771-b7b86c12-96fa-11e7-937f-b567264fef01.png)
After going back:
![screenshot from 2017-09-11 14-08-17](https://user-images.githubusercontent.com/9748680/30273790-c038cf94-96fa-11e7-995a-103cce72e76e.png)

Attribute seems to be not saved with date and then updated incorrectly

**Comment by mnieke** [comment]
I don't understand this issue.
It seems that the child features are not there at the date of the second screenshot.
How could they be expanded?

**Comment by Kv4sir** [comment]
In t1 there are the collapsed 4 features (which are already existent in t0) when going back to t0, they are also collapsed but the decorator is not drawn, so someone might think the features do not exist.
![screenshot from 2017-09-11 14-33-22](https://user-images.githubusercontent.com/9748680/30274535-31b40866-96fe-11e7-858c-c928396a968a.png)

**Comment by mnieke** [comment]
Indeed, this is strange.
@gilengel please have a look at this. Also happens with fixed attached models - not urgent

[NavigationSystem.zip](https://github.com/DarwinSPL/DarwinSPL/files/1292632/NavigationSystem.zip)
