### ISSUE TITLE
Unhandled event loop exception on choosing features

### ISSUE THREAD

**Issue by wartoschi** [DarwinSPL/DarwinSPL#37]
In the configuration Editor, when choosing an new feature for a variant, the Feature doesn't get selected and the log prints a Unhandled event loop exception.

![screenshot from 2017-09-18 12-59-36](https://user-images.githubusercontent.com/31504912/30539142-58d1738e-9c71-11e7-82d4-ef96dafbc04f.png)
![screenshot from 2017-09-18 13-00-12](https://user-images.githubusercontent.com/31504912/30539144-5d3f6c1e-9c71-11e7-9218-42607a11bf27.png)

**Comment by mnieke** [comment]
please upload all models (.hyfeature, .hycontext, .hyconstraints, .hyconfiguration....)

**Comment by wartoschi** [comment]
Here are the models:

[de.tu_bs.cs.isf.jxmapviewer.spl.zip](https://github.com/DarwinSPL/DarwinSPL/files/1310710/de.tu_bs.cs.isf.jxmapviewer.spl.zip)
