### ISSUE TITLE
Attribute Values in Configurator

### ISSUE THREAD

**Issue by mnieke** [DarwinSPL/DarwinSPL#60]
Currently, it is possible to "select" attributes in the configurator.
But if a feature is selected, all of its attributes have to have a value in a valid configuration.
Thus, attributes cannot be selected.
Additionally, their value should be displayed in the configurator if set.

**Comment by alahola** [comment]
Außerdem ist es möglich z.B. boolean-typed Attributen numerische Werte zuzuordnen

**Comment by alahola** [comment]
![image](https://user-images.githubusercontent.com/22443385/32886569-65e825e4-cac1-11e7-8bd2-71c36820fe49.png)

Images shows attributes with default values in configurator. 
The AttributeAssignments are listed below the corresponding feature.
For StringAttributes the default is NULL.
When selecting a feature, all attributes are being selected.

**Comment by alahola** [comment]
![image](https://user-images.githubusercontent.com/22443385/32886678-ba2c9c2a-cac1-11e7-8bb3-3c474c758059.png)

Images shows the dialog which is opened by clicking on a numerical typed attribute.
The dialog is only opened if a corresponding feature is selected - otherwise it is not possible to enter a value for an attribute.

In the image the dialog shows an error message because 'ggg' is not a valid input

**Comment by alahola** [comment]
![image](https://user-images.githubusercontent.com/22443385/32886832-45cf8f6c-cac2-11e7-8662-b04356e1eaf5.png)

Image shows the dialog for editing values for enumeration typed dialogs.
A similar dialog is provided for boolean typed attributes

**Comment by alahola** [comment]
@mnieke

**Comment by mnieke** [comment]
Very good work so far!

One issue left
[FeatureModel.zip](https://github.com/DarwinSPL/DarwinSPL/files/1487558/FeatureModel.zip)
Using this feature model, if I select any version of "New Feature 1", the feature itself is also automatically selected. But the attributes then don't appear on the right-hand side and don't have values.

Additional suggestions for improvement:
1) It would be looking better if the orange box is not in front of the attributes. So just like for the versions.
2) It would be nice if the value for attributes would be written directly next to the attribute in the diagram itself (see modified screenshot)
![grafik](https://user-images.githubusercontent.com/5243830/33018028-fff5eb22-cdf4-11e7-8744-c40025e9f469.png)

**Comment by alahola** [comment]
![image](https://user-images.githubusercontent.com/22443385/34103133-ed0aed8e-e3eb-11e7-99d1-616ea66fd0de.png)

**Comment by alahola** [comment]
![image](https://user-images.githubusercontent.com/22443385/34103150-fc7eec02-e3eb-11e7-915f-65f65b4c18f8.png)
