### ISSUE TITLE
Issue in computeTemporalIntersection() method of class HyEvolutionUtil

### ISSUE THREAD

**Issue by donetti** [DarwinSPL/DarwinSPL#68]
Dear,

In project:  eu.hyvar.evolution
In class:  eu.hyvar.evolution.util.HyEvolutionUtil
In method:  computeTemporalIntersection  at line 505

there is a mismatch in method called:

the line 504 check for ValidUntil property and in line 505 set ValidSince proprerty:

Best regards,
Simone

**Comment by mnieke** [comment]
fixed in b9548ca
