### ISSUE TITLE
Write own wizard in eu.hyvar.context.information.editor

### ISSUE THREAD

**Issue by mnieke** [DarwinSPL/DarwinSPL#69]
The standard generated wizard is not very intuitive as you have to select Model Object you want to create (should be always the context model) and which text encoding should be used (should be always utf8).
So an own wizard would be nice.
Nothing fancy.
Has to be set in the extensions of manifest of eu.hyvar.context.information.editor as wizard.

**Comment by roehrsi** [comment]
# Customized the generated wizard with a default selection:

![image](https://user-images.githubusercontent.com/7250661/37867964-0aa9f790-2fa0-11e8-9a26-05dd88fac1ec.png)
