### ISSUE TITLE
Check  Satisfiability not properly working

### ISSUE THREAD

**Issue by alahola** [DarwinSPL/DarwinSPL#71]
![image](https://user-images.githubusercontent.com/22443385/35349346-f0b0e026-013a-11e8-9d3f-7e48610ebe7b.png)

Meiner Meinung nach sollte im folgenden Fall "model satisfiability" gleich false sein

**Comment by mnieke** [comment]
Das passt schon so.
Das Check Satisfiability überprüft, ob das feature model generell erfüllbar ist - unabhängig von der gewählen Konfiguration (das wäre "Check Configuration Validity")

False wäre es nur, wenn es keine gültige Konfiguration gäbe (äquivalent zu void feature anomaly).
Aber hier sind gültige Konfigurationen:
Root, F1, F3
Root, F1, F2, F3

Oder übersehe ich was? :)
