### ISSUE TITLE
Change Validity not Working Properly

### ISSUE THREAD

**Issue by mnieke** [DarwinSPL/DarwinSPL#73]
The function "right-click -> change validity" is not working properly:

- Dirty flag of the editor is not set (at least when performing it for a feature) 

- element validity is not propagated correctly: For instance, if a feature is valid since t1 until forever and its name / type etc. is valid since t1 until t3 and a second name / type etc. is valid since t3 until forever. Then, the feature validity is changed to be since=t2 and until=null/forever. Then, the validity of the first name / type etc. needs to be set to since=t2 and until=t3 (unchanged). However, it has to be considered that some elements such as names may become obsolete if there is no overlap of the feature validity and the name / type etc. validity. Then, a warning should be displayed that this is the case and if the user agrees to these changes, these names / types etc. have to be deleted completely from the model.
Additionally, the way round is also possible:
Feature validity: since=t2, until=null
Name1 validity: since=t2, until=t3
Name2 validity: since=t3, until=null
Change validity of feature to: since=t1, until=null --> should also entail Name1 validity to be: since=t1, until=t3

Can you please fix this? (not urgent)

**Comment by roehrsi** [comment]
When changing a feature validity, there now is a check for correctly propagating that new validity across all its linear temporal elements.
# Changing validity
## Example:
![image](https://user-images.githubusercontent.com/7250661/36758225-1d65b7c4-1c14-11e8-9f26-0a69918f2a44.png)

### Changing F2 Validity to 02/28/2018/00:00:00:
![image](https://user-images.githubusercontent.com/7250661/36758457-ce26583e-1c14-11e8-8763-cb6a750b5dd2.png)

> notice that only those names change, that are affected by the shift in validity bounds.

# Obsolete elements
When the validity of a feature changes, such that one or more of its elements no longer lie within that new timeframe, the user is prompted to confirm that element's deletion, or chose another valid date.
## Example:
### Changing 'valid until' in above example to 03/02/2018/00:00:00
![image](https://user-images.githubusercontent.com/7250661/36758962-2b03699c-1c16-11e8-86b1-6be690c0bc4c.png)

> the name/type is removed from the element and will no longer appear in the editor at that timestamp.



# Issues:
## Missing Link anomaly
When Name becomes obsolete and has children, what to do with them?
![image](https://user-images.githubusercontent.com/7250661/36759166-cbffb1fc-1c16-11e8-96a3-702970eba674.png)
## Stretching name validity
When the first or last valid name is 'stretched' to fit the new (elongated) feature validity, no parent-child connections are created:
![image](https://user-images.githubusercontent.com/7250661/36759524-f04ef5c6-1c17-11e8-9b6e-ab1cab612d05.png)![image](https://user-images.githubusercontent.com/7250661/36759579-29e1516c-1c18-11e8-9072-8961e7b76f85.png)

### This happens, when the feature did not exist at that time yet:

![image](https://user-images.githubusercontent.com/7250661/36759614-42b1d220-1c18-11e8-8b3d-128a1aed0d3b.png)

**Comment by mnieke** [comment]
Good work, this looks nice so far.

I do not fully understand the "Missing Link anomaly" issue.
As I understood it, you did the following:
F2 (since=null, until=null) and a child of it F3 (since=null, until=null).
Then you change F2 (since=t1, until=null) and you do not know what to do with feature F3?
If that's the issue, we postpone its solution. That's rather complex and I want a student to work in a thesis on this topic.

The same applies for the "Stretching name validity" issue.
If that are the only open points, I think we can close this issue 👍

**Comment by roehrsi** [comment]
That is the long and short of it, yes.
I will just disable the change in that case and display an error message.
